version: '3.3'
services:
    api:
        build: .
        image: mcshrt.us:latest
        ports:
            - 5059:5000
        volumes:
            - type: bind
              source: .
              target: /app/