version: '3.3'
services:
    api:
        build: .
        image: mcshrt.us:latest
        ports:
            - 5059:5059
        volumes:
            - type: bind
              source: .
              target: /app/
        networks:
          - nginx-proxy-manager_default